#!/usr/bin/python3
import unittest
from selenium import webdriver
from selenium.webdriver.common.by import By
import time

welc = "Congratulations! You have successfully registered!"
def registration(link):
    with webdriver.Chrome() as browser:
        browser.get(link)

        input1 = browser.find_element(By.CLASS_NAME, "form-control.first")
        input1.send_keys("Ivan")
        input2 = browser.find_element(By.XPATH, "//*[@class='form-control second']")
        input2.send_keys("Petrov")
        input3 = browser.find_element(By.XPATH, "//div[3]/input")
        input3.send_keys("csdvsv@sca.com")
        button = browser.find_element(By.CSS_SELECTOR, "button.btn")
        button.click()
        
        time.sleep(1)
        welcome_text_elt = browser.find_element(By.TAG_NAME, "h1")

        return welcome_text_elt.text

class TestsForPages(unittest.TestCase):
    def test_first_page(self):
        p1 = registration("http://suninjuly.github.io/registration1.html")
        self.assertEqual(p1, welc)

    def test_second_page(self):
        p2 = registration("http://suninjuly.github.io/registration2.html")
        self.assertEqual(p2, welc)


if __name__ == "__main__":
    unittest.main()
