#!/usr/bin/python3
from selenium import webdriver
from selenium.webdriver.common.by import By
import unittest, time


def get_text(link):
    browser = webdriver.Chrome()
    browser.get(link)
    input1 = browser.find_element(By.CLASS_NAME, "form-control.first")
    input1.send_keys("Ivan")
    input2 = browser.find_element(By.XPATH, "//*[@class='form-control second']")
    input2.send_keys("Petrov")
    input3 = browser.find_element(By.XPATH, "//div[3]/input")
    input3.send_keys("csdvsv@sca.com")
    button = browser.find_element(By.CSS_SELECTOR, "button.btn")
    button.click()
    time.sleep(1)
    welcome_text_elt = browser.find_element(By.TAG_NAME, "h1")
    welcome_text = welcome_text_elt.text    
    browser.quit()
    return welcome_text

class TestAbs(unittest.TestCase):

    def test_link1(self):
        link1 = get_text("http://suninjuly.github.io/registration1.html")
        self.assertEqual("Congratulations! You have successfully registered!", link1)

    def test_link2(self):
        link2 = get_text("http://suninjuly.github.io/registration2.html")
        self.assertEqual("Congratulations! You have successfully registered!", link2)

if __name__ == "__main__":
    unittest.main(warnings='ignore')
